from __future__ import annotations

NETWORK_NAME = "ZYRA_NETWORK"
NETWORK_API_VERSION = "v1"
NETWORK_PROTOCOL_VERSION = "1"

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8000

ENV_DEVELOPMENT = "development"
ENV_TESTING = "testing"
ENV_STAGING = "staging"
ENV_PRODUCTION = "production"

LOG_LEVELS = frozenset(
    {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
)

__all__ = [
    "NETWORK_NAME",
    "NETWORK_API_VERSION",
    "NETWORK_PROTOCOL_VERSION",
    "DEFAULT_HOST",
    "DEFAULT_PORT",
    "ENV_DEVELOPMENT",
    "ENV_TESTING",
    "ENV_STAGING",
    "ENV_PRODUCTION",
    "LOG_LEVELS",
]
